# Generated by Django 3.1 on 2020-10-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201006_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('contents', models.TextField(max_length=200, verbose_name='Contents')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
